"""log.user_id

Revision ID: 07ea1a401dc0
Revises: 043a8a745f8e
Create Date: 2024-04-07 23:00:06.592834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07ea1a401dc0'
down_revision = '043a8a745f8e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requestlog', sa.Column('user_id', sa.String(length=50), nullable=True))
    op.alter_column('requestlog', 'service_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index('ix_requestlog_authorization', table_name='requestlog')
    op.drop_index('ix_requestlog_id', table_name='requestlog')
    op.drop_index('ix_requestlog_ip', table_name='requestlog')
    op.drop_index('ix_requestlog_method', table_name='requestlog')
    op.drop_index('ix_requestlog_request', table_name='requestlog')
    op.drop_index('ix_requestlog_service_name', table_name='requestlog')
    op.drop_index('ix_requestlog_trace', table_name='requestlog')
    op.drop_column('requestlog', 'authorization')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requestlog', sa.Column('authorization', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.create_index('ix_requestlog_trace', 'requestlog', ['trace'], unique=False)
    op.create_index('ix_requestlog_service_name', 'requestlog', ['service_name'], unique=False)
    op.create_index('ix_requestlog_request', 'requestlog', ['request'], unique=False)
    op.create_index('ix_requestlog_method', 'requestlog', ['method'], unique=False)
    op.create_index('ix_requestlog_ip', 'requestlog', ['ip'], unique=False)
    op.create_index('ix_requestlog_id', 'requestlog', ['id'], unique=False)
    op.create_index('ix_requestlog_authorization', 'requestlog', ['authorization'], unique=False)
    op.alter_column('requestlog', 'service_name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('requestlog', 'user_id')
    # ### end Alembic commands ###
