"""create vertices table

Revision ID: 41b0d43c6d3f
Revises: 94d11a46f47f
Create Date: 2024-11-26 14:50:10.906380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41b0d43c6d3f'
down_revision = '94d11a46f47f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
