"""add

Revision ID: 94d11a46f47f
Revises: 83aa7d9a2ec8
Create Date: 2024-10-19 12:44:26.752863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94d11a46f47f'
down_revision = '83aa7d9a2ec8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vertex', sa.Column('endx', sa.Float(), nullable=True))
    op.add_column('vertex', sa.Column('endy', sa.Float(), nullable=True))
    op.add_column('vertex', sa.Column('startx', sa.Float(), nullable=True))
    op.add_column('vertex', sa.Column('starty', sa.Float(), nullable=True))
    op.add_column('vertex', sa.Column('pox', sa.Float(), nullable=True))
    op.add_column('vertex', sa.Column('poy', sa.Float(), nullable=True))
    op.drop_column('vertex', 'y')
    op.drop_column('vertex', 'x')
    op.drop_column('vertex', 'description')
    op.drop_column('vertex', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vertex', sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('vertex', sa.Column('description', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('vertex', sa.Column('x', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('vertex', sa.Column('y', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('vertex', 'poy')
    op.drop_column('vertex', 'pox')
    op.drop_column('vertex', 'starty')
    op.drop_column('vertex', 'startx')
    op.drop_column('vertex', 'endy')
    op.drop_column('vertex', 'endx')
    # ### end Alembic commands ###
