"""empty message

Revision ID: da38f1cb6255
Revises: 41b0d43c6d3f
Create Date: 2025-01-12 07:40:17.241425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da38f1cb6255'
down_revision = '41b0d43c6d3f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_created'), 'bot', ['created'], unique=False)
    op.create_index(op.f('ix_bot_id'), 'bot', ['id'], unique=False)
    op.create_index(op.f('ix_bot_is_deleted'), 'bot', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_bot_modified'), 'bot', ['modified'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bot_modified'), table_name='bot')
    op.drop_index(op.f('ix_bot_is_deleted'), table_name='bot')
    op.drop_index(op.f('ix_bot_id'), table_name='bot')
    op.drop_index(op.f('ix_bot_created'), table_name='bot')
    op.drop_table('bot')
    # ### end Alembic commands ###
