name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # Set up Poetry
    - name: Set up Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    # Navigate to the 'app' directory where pyproject.toml is located
    - name: Install dependencies with Poetry
      run: |
        cd app  # Change to the app directory where pyproject.toml is located
        poetry install --no-interaction --no-root
    
    # Build the Docker image
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
